server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coder-club?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    password: Y/TCQpSZTPrzNXPt/YYKYsPGQ75scGhjC0bYGctG4W77BF+9/TK57IuDT5rUbOuwp6CHL5F3EJLcCDCNsnI+2w==
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey}
      min-idle: 20
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
  elasticsearch:
    rest:
      uris: http://192.168.79.135:9200
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 192.168.79.135
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间
    timeout: 5s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKHEQNJ8kC7zGfbaS5Gy53ToSL0v7tGQfMwNcY4T8viN7QqIYOCoQk22kDefjFm9V3eMarRomLpi+zYaLJEkHFUCAwEAAQ==
logging:
  config: classpath:log4j2-spring.xml
es:
  cluster:
    esConfigs[0]:
      name: 610119a868fb
      nodes: 192.168.79.135:9200